/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Permission', null, global);
/**
 * @enum {number}
 */
proto.Permission = {
  EDIT_PROJECT: 0,
  SELECT_PROJECT_MODULES: 1,
  MANAGE_MEMBERS: 2,
  VIEW_MEMBERS: 3,
  MANAGE_VERSIONS: 4,
  MANAGE_TYPES: 5,
  ADD_SUBPROJECTS: 6,
  COPY_PROJECTS: 7,
  VIEW_WORK_PACKAGES: 8,
  ADD_WORK_PACKAGES: 9,
  EDIT_WORK_PACKAGES: 10,
  MOVE_WORK_PACKAGES: 11,
  ADD_WORK_PACKAGE_NOTES: 12,
  EDIT_WORK_PACKAGE_NOTES: 13,
  EDIT_OWN_WORK_PACKAGE_NOTES: 14,
  MANAGE_CATEGORIES: 15,
  EXPORT_WORK_PACKAGES: 16,
  DELETE_WORK_PACKAGES: 17,
  MANAGE_WORK_PACKAGE_RELATIONS: 18,
  MANAGE_SUBTASKS: 19,
  MANAGE_PUBLIC_QUERIES: 20,
  SAVE_QUERIES: 21,
  VIEW_WORK_PACKAGE_WATCHERS: 22,
  ADD_WORK_PACKAGE_WATCHERS: 23,
  DELETE_WORK_PACKAGE_WATCHERS: 24,
  ASSIGN_VERSIONS: 25,
  VIEW_TIME_ENTRIES: 26,
  LOG_TIME: 27,
  EDIT_TIME_ENTRIES: 28,
  VIEW_OWN_TIME_ENTRIES: 29,
  EDIT_OWN_TIME_ENTRIES: 30,
  MANAGE_PROJECT_ACTIVITIES: 31,
  MANAGE_NEWS: 32,
  COMMENT_NEWS: 33,
  VIEW_WIKI_PAGES: 34,
  LIST_ATTACHMENTS: 35,
  MANAGE_WIKI: 36,
  MANAGE_WIKI_MENU: 37,
  RENAME_WIKI_PAGES: 38,
  CHANGE_WIKI_PARENT_PAGE: 39,
  DELETE_WIKI_PAGES: 40,
  EXPORT_WIKI_PAGES: 41,
  VIEW_WIKI_EDITS: 42,
  EDIT_WIKI_PAGES: 43,
  DELETE_WIKI_PAGES_ATTACHMENTS: 44,
  PROTECT_WIKI_PAGES: 45,
  BROWSE_REPOSITORY: 46,
  COMMIT_ACCESS: 47,
  MANAGE_REPOSITORY: 48,
  VIEW_CHANGESETS: 49,
  VIEW_COMMIT_AUTHOR_STATISTICS: 50,
  MANAGE_FORUMS: 51,
  ADD_MESSAGES: 52,
  EDIT_MESSAGES: 53,
  EDIT_OWN_MESSAGES: 54,
  DELETE_MESSAGES: 55,
  DELETE_OWN_MESSAGES: 56,
  VIEW_CALENDAR: 57,
  VIEW_DOCUMENTS: 58,
  MANAGE_DOCUMENTS: 59,
  VIEW_OWN_HOURLY_RATE: 60,
  VIEW_HOURLY_RATES: 61,
  EDIT_OWN_HOURLY_RATE: 62,
  EDIT_HOURLY_RATES: 63,
  VIEW_COST_RATES: 64,
  LOG_OWN_COSTS: 65,
  LOG_COSTS: 66,
  EDIT_OWN_COST_ENTRIES: 67,
  EDIT_COST_ENTRIES: 68,
  VIEW_COST_OBJECTS: 69,
  VIEW_COST_ENTRIES: 70,
  VIEW_OWN_COST_ENTRIES: 71,
  EDIT_COST_OBJECTS: 72,
  SAVE_COST_REPORTS: 73,
  SAVE_PRIVATE_COST_REPORTS: 74,
  VIEW_MEETINGS: 75,
  CREATE_MEETINGS: 76,
  EDIT_MEETINGS: 77,
  DELETE_MEETINGS: 78,
  MEETINGS_SEND_INVITE: 79,
  CREATE_MEETING_AGENDAS: 80,
  CLOSE_MEETING_AGENDAS: 81,
  SEND_MEETING_AGENDAS_NOTIFICATION: 82,
  SEND_MEETING_AGENDAS_ICALENDAR: 83,
  CREATE_MEETING_MINUTES: 84,
  SEND_MEETING_MINUTES_NOTIFICATION: 85,
  VIEW_MASTER_BACKLOG: 86,
  VIEW_TASKBOARDS: 87,
  UPDATE_SPRINTS: 88,
  SHOW_BOARD_VIEWS: 89,
  MANAGE_BOARD_VIEWS: 90,
  MANAGE_OVERVIEW: 91
};

goog.object.extend(exports, proto);
